
language: elm

install:
  - npm install -g create-elm-app@3.0.6

script:
  - elm-format --validate
  - elm-app build

deploy:
  provider: surge
  project: ./build/
  domain: kids-math-quiz.surge.sgh
  skip_cleanup: true
